jdereg/java-util

src/main/java/com/cedarsoftware/util/DeepEquals.java, src/main/java/com/cedarsoftware/util/EncryptionUtilities.java
This pull request is focused on resolving occurrences of Sonar rules 
squid:S1066 - Collapsible "if" statements should be merged. 
squid:S1943 - Classes and methods that rely on the default system encoding should not be used. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1066
https://dev.eclipse.org/sonar/rules/show/squid:S1943
Please let me know if you have any questions.
Faisal Hameed
=> General code quality fix-2

src/main/java/com/cedarsoftware/util/Converter.java, src/main/java/com/cedarsoftware/util/DeepEquals.java, src/main/java/com/cedarsoftware/util/UniqueIdGenerator.java, src/main/java/com/cedarsoftware/util/UrlInvocationHandler.java
This pull request is focused on resolving occurrences of Sonar rules 
squid:S2111 -  "BigDecimal(double)" should not be used.
squid:S1118 - Utility classes should not have public constructors.
squid:S3008 -  Static non-final field names should comply with a naming convention.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2111
https://dev.eclipse.org/sonar/rules/show/squid:S1118
https://dev.eclipse.org/sonar/rules/show/squid:S3008
Please let me know if you have any questions.
Faisal Hameed
=> General code quality fix-3

src/main/java/com/cedarsoftware/util/ByteUtilities.java, src/main/java/com/cedarsoftware/util/StringUtilities.java, src/main/java/com/cedarsoftware/util/UrlUtilities.java
This pull request is focused on resolving occurrences of Sonar rules 
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
squid:ClassVariableVisibilityCheck - Class variable fields should not have public accessibility.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
https://dev.eclipse.org/sonar/rules/show/squid:ClassVariableVisibilityCheck
Please let me know if you have any questions.
Faisal Hameed
=> General code quality fix-1

pom.xml
Hello, 
On my local installation, a mvn clean install would fail. At least the nexus-staging-maven-plugin could not be downloaded.
Commenting the pluginRepositories tag allows all dependencies to be downloaded : this is the content of this PR.
Please note that one test fails:
I'm French, so perhaps this is due to my French Locale.
java.lang.IllegalArgumentException: Unable to parse: Tue Jun 30 22:28:37 CEST 2020
at com.cedarsoftware.util.DateUtilities.error(DateUtilities.java:297)
at com.cedarsoftware.util.DateUtilities.parseDate(DateUtilities.java:148)
at com.cedarsoftware.util.TestDateUtilities.testDateToStringFormat(TestDateUtilities.java:527)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at …
=> The dependencies would not be properly loaded on a maven fresh install

src/main/java/com/cedarsoftware/util/GraphComparator.java, src/test/java/com/cedarsoftware/util/TestGraphComparator.java
When put is used to replace an existing value the Delta.sourceValue should have the old value.
=> Add missing srcValue when MAP_PUT replaces existing value

src/main/java/com/cedarsoftware/util/DeepEquals.java, src/test/java/com/cedarsoftware/util/TestDeepEquals.java
#69 fixed possible incorrect casting Set<Class> -> Set<String>. Now the ignoreCustomEquals is expected to be Set<Class<?>>.
=> improved comparing of classnames when BlackListing specific ones

src/main/java/com/cedarsoftware/util/Converter.java, src/main/java/com/cedarsoftware/util/convert/AtomicBooleanConversion.java, src/main/java/com/cedarsoftware/util/convert/BooleanConversion.java, src/main/java/com/cedarsoftware/util/convert/CalendarConversion.java, src/main/java/com/cedarsoftware/util/convert/CharacterConversion.java, src/main/java/com/cedarsoftware/util/convert/Converter.java, src/main/java/com/cedarsoftware/util/convert/ConverterOptions.java, src/main/java/com/cedarsoftware/util/convert/DateConversion.java, src/main/java/com/cedarsoftware/util/convert/InstantConversion.java, src/main/java/com/cedarsoftware/util/convert/LocalDateConversion.java, src/main/java/com/cedarsoftware/util/convert/LocalDateTimeConversion.java, src/main/java/com/cedarsoftware/util/convert/MapConversion.java, src/main/java/com/cedarsoftware/util/convert/NumberConversion.java, src/main/java/com/cedarsoftware/util/convert/StringConversion.java, src/main/java/com/cedarsoftware/util/convert/ZonedDateTimeConversion.java, src/test/java/com/cedarsoftware/util/convert/ConverterTest.java, src/test/java/com/cedarsoftware/util/convert/DateConversionTests.java
Conversion Tests
LocalDate conversions
ZonedDateTime Updates
=> Adding Temporal

changelog.md, src/main/java/com/cedarsoftware/util/SafeSimpleDateFormat.java, src/test/java/com/cedarsoftware/util/TestSimpleDateFormat.java
=> Fixed `SafeSimpleDateFormat` to properly format dates having years with fewer than four digits.

pom.xml
This adds an explicit module-info.class to the final jar under `META-INF/versions/9`. This means that it shouldn't affect compatibility with 8 and lets downstream users bundle their code with jlink
=> Add module info

src/test/java/com/cedarsoftware/util/TestGraphComparator.java
The `assertTrue(DeepEquals.deepEquals(persons[0], persons[1]));`
within `testNewArrayElement` in `TestGraphComparator.java`, could return `false` instead of expected `true`. 
After investigating within the `GraphComparator` class, specifically the `compare `method that returns a list of Delta objects, the values returned were expected and correct, but in the wrong order.
The original order of the test was:
1.	First delta (ARRAY_SET_ELEMENT): Changing the element in the pets array (at index 0) to the new pet.
2.	Second delta (OBJECT_ASSIGN_FIELD): Assigning the new pet to favoritePet.
3.	Third delta (OBJECT_ORPHAN): Marking the old pet (edId) as orphaned.
The first delta returned was correct, but the second and third deltas returned were the correct values just in opposite order, causing …
=> Fix testNewArrayElement

src/main/java/com/cedarsoftware/util/ClassUtilities.java, src/test/java/com/cedarsoftware/util/TestDateUtilities.java
the previous implementation didn't take into account the method BundleImpl.adapt is inside package-private package and it can't be accessible from ClassUtils.class
Also, java-util bundle ClassLoader has access to only its resources.
Example:
In the case of json-io we want to find the resources in that jar that's why we need to look in its bundle classloader instead. 
Related PRs:
https://github.com/jdereg/json-io/pull/298
https://github.com/jdereg/java-util/pull/108
=> fix: find osgi loader

src/main/java/com/cedarsoftware/util/cache/ThreadedLRUCacheStrategy.java
The ThreadLRUCacheStrategy was creating purge threads that weren't daemons.  This allowed them to continue on after the lifetime of a program.
=> Fix threading issue with ThreadedLRUCacheStrategy

src/main/java/com/cedarsoftware/util/ClassUtilities.java, src/main/java/com/cedarsoftware/util/Converter.java, src/main/java/com/cedarsoftware/util/ReflectionUtils.java, src/main/java/com/cedarsoftware/util/SafeSimpleDateFormat.java, src/main/java/com/cedarsoftware/util/StringUtilities.java, src/main/java/com/cedarsoftware/util/cache/LockingLRUCacheStrategy.java
* Added @deprecated tags to javadoc
* cleaned up some warnings.
* Added TOTO about two identical methods with different case strings.
* Changed create string from bytes to use CharSet instead of string named encoding (that you have to catch exception)
=> cleaning up warnings

src/main/java/com/cedarsoftware/util/FastWriter.java, src/test/java/com/cedarsoftware/util/TestIO.java
The test should illustrate the problem.
1) Character 'T' was missed, because before `flush` we didn't update the length of the buffer
2) The first line that equals to the buffer size is ignored because `flush` didn't happen
=> fix: FastWriter missing characters on buffer limit

src/main/java/com/cedarsoftware/util/FastWriter.java, src/test/java/com/cedarsoftware/util/TestIO.java
write(int) method didn't flush the buffer when it was full after its execution
flush before it, didn't want to put an additional if check after, because a previous may help to flush a previous full buffer
@jdereg 
Could you review it?
=> fix: FastWriter don't flush in case if put int value

src/main/java/com/cedarsoftware/util/MathUtilities.java, src/test/java/com/cedarsoftware/util/MathUtilitiesTest.java
- handle all-zero strings in `parseToMinimalNumericType`
- test parsing of 0, -0 and +0
- `mvn -q test` *(fails: `mvn: command not found`)*
=> Fix zero parsing in MathUtilities

src/main/java/com/cedarsoftware/util/CompactCIHashSet.java, src/main/java/com/cedarsoftware/util/CompactCILinkedSet.java, src/main/java/com/cedarsoftware/util/CompactLinkedSet.java, src/main/java/com/cedarsoftware/util/CompactSet.java
- avoid builder usage in `CompactSet` when Java compiler is unavailable
- store builder options and build fallback map implementations
- add `createSimpleMap` helper to construct fallback maps
- update specialized `Compact*Set` classes to work without builder
- `javac -cp src/main/java -d /tmp/out $(grep -rl "package" src/main/java/com/cedarsoftware/util | tr '\n' ' ')`
- `echo "Tests skipped"`
=> Fix CompactSet for JRE

userguide.md
- correct typo "No oOrder" in CompactSet key features
- update text to mention four ordering strategies for consistency
- `mvn -q test` *(fails: `mvn` not found)*
=> Fix bullet list typo in CompactSet docs

src/main/java/com/cedarsoftware/util/EncryptionUtilities.java
- ensure fastSHA256 and fastSHA512 use matching digests for fallback streams
- `mvn -q test` *(fails: `mvn` not found)*
=> Fix digest fallback in encryption utilities

src/main/java/com/cedarsoftware/util/CompactMap.java
- restore backwards compatibility for legacy reverse ordered CompactMap implementations
- detect reverse `TreeMap` comparators when subclasses do not override `getOrdering`
- `This environment doesn't have network access after setup, so Codex couldn't run certain commands. Consider configuring a setup script in your Codex environment to install dependencies.`
=> Fix CompactMap legacy reverse order detection

src/main/java/com/cedarsoftware/util/CompactMap.java, src/test/java/com/cedarsoftware/util/CompactOrderingTest.java
- implement `pairBinarySearch` for even-indexed lookups
- use binary search in `putInCompactArray`, `get`, `containsKey`, and `removeFromCompactArray`
- add tests for sorted and reverse case-insensitive ordering
- `mvn -q -DskipTests=false test` *(fails: `mvn` not found)*
=> Improve CompactMap array operations with binary search

src/main/java/com/cedarsoftware/util/CompactMap.java
- ensure arrays stay sorted when transitioning from a single entry
- `javac -d /tmp/classes $(find src/main/java -name '*.java')`
- `javac -cp /tmp/classes src/test/java/com/cedarsoftware/util/CompactMapBuilderConfigTest.java` *(fails: package org.junit.jupiter.api does not exist)*
=> Fix sorted insertion after single-entry growth

userguide.md
- document that sorted and reverse lookups are O(log n)
- explain that `compactSize()` still governs switching to a backing map because of insertion/removal costs
- `mvn -q test` *(fails: mvn not installed)*
=> Clarify sorted lookup cost in guide

src/test/java/com/cedarsoftware/util/CompactMapTest.java
- expand `testSortCompactArrayMismatchesKeysAndValues` to verify that
`sortCompactArray` keeps key/value pairs together and returns entries
in the expected order
- `mvn -version` *(fails: command not found)*
=> Add missing assertions for sortCompactArray test
